name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]  # main 브랜치에 push될 때 실행

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

# 1. 인증 부분 변경
    - name: Google Auth        # 변경됨
      id: auth                 # 변경됨
      uses: google-github-actions/auth@v1  # 변경됨
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # 추가됨
        token_format: 'access_token'  # 추가됨

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy Backend
      run: |
        cd back  # 백엔드 디렉토리로 이동
        gcloud app deploy  # App Engine에 직접 배포

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build Frontend
      env:
        VITE_KAKAO_APP_KEY: ${{ secrets.VITE_KAKAO_APP_KEY }}  # GitHub secrets에 추가 필요
      run: |
        cd front  # 프론트엔드 디렉토리로 이동
        npm install
        npm run build

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        token_format: 'access_token'  # 추가됨
        access_token_lifetime: '300s'  # 추가됨

    - name: Deploy to Cloud Storage
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Upload to Cloud Storage
      run: |
        cd front/dist  # 빌드된 파일이 있는 디렉토리로 이동
        gsutil -m rsync -r . gs://${{ secrets.GCP_BUCKET_NAME }}